### ISSUE TITLE
You can't donate more than $1 with Paypal.

### ISSUE THREAD

**Issue by ebarranco** [synfig/www.synfig.org#5] opened 2018-09-15 22:15 UTC
When you try to donate any other amount than the 1 dollar default in the page of support synfig development, it doesn't show paypal option on the payment section. (chrome/firefox)
[You can see a video here.](https://www.dropbox.com/s/q54is21h1d22w65/2018-09-15%2017-01-53.mov?dl=0)

**Comment by morevnaproject** [comment] 2018-09-16 07:11
Thank you for reporting! I have fixed the issue by changing the donation system. ^__^"
Should be working now - https://www.synfig.org/donate/

**Comment by ebarranco** [comment] 2018-09-16 07:35
Now it's working but it gave me the page in Russian.
![screenshot_20180916_023112](https://user-images.githubusercontent.com/11136544/45594046-35c30000-b959-11e8-8a1b-f5dd7b0ae0b4.png)

**Comment by morevnaproject** [comment] 2018-09-16 07:38
Um, weird... Let me try to do something about that...

**Comment by morevnaproject** [comment] 2018-09-16 07:45
I have made some tweaks. Can you please test again?

**Comment by ebarranco** [comment] 2018-09-16 16:39
@morevnaproject  Nope, I still have the login russian paypal page.

**Comment by morevnaproject** [comment] 2018-09-17 10:20
@ebarranco Got it, thank you. Working on alternative solution.

**Comment by morevnaproject** [comment] 2018-09-17 11:46
@ebarranco Reworked donation system again - https://www.synfig.org/donate/.
Should be working now. ^__^

**Comment by ebarranco** [comment] 2018-09-17 18:40
@morevnaproject Yeah, it's working now. Thanks.

**Comment by morevnaproject** [comment] 2018-09-18 09:48
@ebarranco Thank you very much for your contribution!
I have refunded your donation because I want to ask you to make one more test.
Here is a one more version of the page with some fixes - https://www.synfig.org/donate/
![screenshot_005](https://user-images.githubusercontent.com/332868/45679304-907b7800-bb62-11e8-8ff3-8e0e040e224b.png)

Can you please check if PayPal checkout will be in correct language and if the donation will pass thorugh?
Thank you!

**Comment by ebarranco** [comment] 2018-09-18 17:27
@morevnaproject Yes, it seems to work fine now, the language now is Spanish that is the correct for my region, but paypal rejected my pay, I think is because you just reimburse me. I'll try again tomorrow.

**Comment by morevnaproject** [comment] 2018-09-20 14:28
@ebarranco I am strongly suspect the problem is not because of recent refund. Most probably it is because this form is not compatible with the type of my PayPal account. Well, anyway it was worth trying. I am reverting to solution that worked for you previously. Thank you for your help! ^__^

**Closed as completed by morevnaproject** 2018-09-20 14:28 UTC

**Comment by ebarranco** [comment] 2018-09-20 17:15
@morevnaproject You right, I tried a couple of times without success, now that you changed it , I can do it just fine. The language is fine too. Just your name in my transactions is still in russian characters, I suspect that is your name,  "Дмитриев Константин"

**Comment by morevnaproject** [comment] 2018-09-21 15:45
Yes, that's my name written in Cyrillic. Unfortunately, I have no control to change it for Latin. ^__^

Thank you again for your help and support!
